dai-shi/remote-faces

web/public/main.js
=> r84 without change

.github/workflows/gh-pages.yml, web/public/main.js
=> r85 without change

web/src/capture/webcam.ts, web/src/components/SingleRoom.tsx, web/src/hooks/useFaceImages.ts, web/src/hooks/useVideoDevices.ts
close #15 
I might be better to store configuration, but it's less important for now. It will be a future task.
=> select camera

web/src/components/SingleRoom.tsx, web/src/components/SingleRoomEntrance.tsx, web/src/utils/url.ts
Close #32 
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/enter-room-link/web/
=> feat: enter room link

web/src/components/SingleRoom.tsx
add hide config button
Preview URL: https://codesandbox.io/s/github/kobatastu/remote-faces/tree/feat/add-config-button/web/
=> feat: add config button

web/src/components/SingleRoom.tsx, web/src/hooks/useFaceImages.ts, web/src/hooks/useRoom.ts, web/src/network/room.ts
This is refactoring useFaceImages with useRoom. It should be much easier to add features with new building blocks.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/use-room-hook/web/
=> refactor with useRoom

web/src/components/MomentaryChat.css, web/src/components/MomentaryChat.tsx, web/src/components/SingleRoom.tsx, web/src/components/SingleRoomEntrance.tsx, web/src/hooks/useMomentaryChat.ts, web/tsconfig.json
Close #40 
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/momentary-chat/web/
=> feat: momentary chat

web/src/hooks/useRoom.ts, web/src/network/room.ts
Close #50 
Preview URL: https://codesandbox.io/s/github/daishi/remote-faces/tree/feat/reconnect-on-error/web/
=> feat: reconnect on error

web/src/network/peerUtils.ts, web/src/network/room.ts
This should fix most of current issues around network failure/reconnect.
There might still be some edge cases that won't work well, and we'll probably revisit this again.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/better-network-reconnect/web/
=> better network handling

web/src/components/FaceImages.css, web/src/components/FaceImages.tsx, web/src/components/MomentaryChat.css, web/src/components/SingleRoom.css, web/src/components/SingleRoom.tsx
I propose to relocate chat room
Preview URL: https://codesandbox.io/s/github/kobatastu/remote-faces/tree/feat/relocate-chatroom/web/
=> relocate chatroom

web/src/components/MomentaryChat.css, web/src/components/MomentaryChat.tsx
I propose design like slack
please try below code sandbox
Preview URL: https://codesandbox.io/s/github/kobatastu/remote-faces/tree/feat/add-design/web/
=> add design like slack

web/src/components/MomentaryChat.css, web/src/components/MomentaryChat.tsx
I propose reaction button design like slack
Preview URL: https://codesandbox.io/s/github/kobatastu/remote-faces/tree/feat/modify-design/web/
=> change reaction stamp style

web/public/index.html, web/src/components/FaceImages.css, web/src/components/FaceImages.tsx, web/src/components/SingleRoom.tsx, web/src/hooks/useFaceImages.ts, web/src/hooks/useFaceVideos.ts, web/src/hooks/useRoom.ts, web/src/media/capture.ts, web/src/media/video.ts, web/src/network/peerUtils.ts, web/src/network/room.ts
Close #44.
- attach audio track -> #56
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/live-mode/web/
=> video support (no audio yet)

web/src/components/FaceImages.tsx, web/src/components/SingleRoom.tsx, web/src/hooks/useFaceImages.ts, web/src/hooks/useFaceVideos.ts, web/src/hooks/useMomentaryChat.ts, web/src/hooks/useRoom.ts, web/src/network/peerUtils.ts, web/src/network/room.ts
Refactoring with breaking changes in the network protocol.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/chore/refactor-network/web/
=> big refactor in network: put userId in connMap

web/src/components/FaceImages.tsx, web/src/hooks/useFaceVideos.ts, web/src/media/video.ts, web/src/network/peerUtils.ts, web/src/network/room.ts
Refactor again.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/chore/network-with-track/web/
=> media stream using data channel negotiation

web/package.json, web/src/components/FaceImages.tsx, web/src/components/ScreenShare.css, web/src/components/ScreenShare.tsx, web/src/components/SingleRoom.tsx, web/src/hooks/useFaceImages.ts, web/src/hooks/useFaceVideos.ts, web/src/hooks/useNicknameMap.ts, web/src/hooks/useRoom.ts, web/src/hooks/useScreenShare.ts, web/src/media/screen.ts, web/src/media/video.ts, web/src/network/peerUtils.ts, web/src/network/room.ts
Close #57.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/screen-share/web/
=> feat: screen share

web/package.json, web/src/components/SingleRoom.css, web/src/components/SingleRoom.tsx, web/src/utils/emoji.ts, yarn.lock
I'm sending new pull request instead of #66 .
In this, Emoji status is sent with status message.
Preview URL: https://codesandbox.io/s/github/tell-y/remote-faces/tree/feat/adopt-emoji-mart/web/
=> adopt rich emoji tool and send emoji with status message

web/src/network/peerUtils.ts, web/src/network/room.ts, web/src/utils/url.ts
- use only part of room id for signaling server and add check in data channel payload
- custom peerjs server from url hash
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/network-secure-and-custom/web/
=> chore: more secure network and custom server

web/src/components/SingleRoomEntrance.tsx, web/src/hooks/useFaceImages.ts, web/src/hooks/useMomentaryChat.ts, web/src/hooks/useNicknameMap.ts, web/src/network/peerUtils.ts, web/src/network/room.ts, web/src/utils/crypto.ts, web/src/utils/storage.ts, web/src/utils/types.ts
It might be over engineered, but it's more secure now.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/chore/network-encryption/web/
=> chore: encryption on data channel

web/src/components/MomentaryChat.css, web/src/components/MomentaryChat.tsx, web/src/hooks/useMomentaryChat.ts
I add the time to chat
Preview URL: https://codesandbox.io/s/github/kobatastu/remote-faces/tree/feat/add-time/web/
=> add time to chat

web/src/components/MomentaryChat.css, web/src/components/MomentaryChat.tsx
We can click reaction button under comment 
Preview URL: https://codesandbox.io/s/github/kobatastu/remote-faces/tree/feat/anable-click-reaction-button/web/
=> add click function under reaction button

web/src/components/CollabWhiteBoard.css, web/src/components/CollabWhiteBoard.tsx, web/src/components/MomentaryChat.css, web/src/components/SingleRoom.tsx, web/src/utils/crypto.ts, web/src/utils/excalidraw.ts
Close #77
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/collab-white-board/web/
=> feat: add collab white board

web/src/components/SingleRoom.tsx, web/src/components/VideoShare.css, web/src/components/VideoShare.tsx, web/src/hooks/useFaceVideos.ts, web/src/hooks/useVideoShare.ts, web/src/media/video.ts
Close #67.
The layout is bad for now, and should be fixed.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/video-share/web/
=> feat: add video share

web/src/components/SingleRoom.css, web/src/components/SingleRoom.tsx, web/src/components/UserProfile.css, web/src/components/UserProfile.tsx
I add user profile area which contains nickname, emoji and status message.
And I move network status into setting box.
Preview URL: https://codesandbox.io/s/github/tell-y/remote-faces/tree/feat/owner-ui/web/
=> Add user profile area and modify style

web/src/components/MomentaryChat.css, web/src/components/MomentaryChat.tsx, web/src/components/SingleRoom.css, web/src/components/SingleRoom.tsx
Chat input area is put at bottom and chat messages are listed from bottom to top.
Preview URL: https://codesandbox.io/s/github/tell-y/remote-faces/tree/feat/chat-ui/web/
=> Change chat UI

web/src/network/room.ts
This is just a workaround.
For a complete solution, we'd need to revisit the entire structure (or at least `src/network/room.ts` and `src/hooks/useRoom.ts`).
At this moment, I'm not very confident if the current "1 RTCPeerConnection + multiple (and dynamic) tracks" approach is super appropriate.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/live-mode-init/web/
=> Make initialization of Live Mode more stable

web/src/components/VideoShare.css, web/src/components/VideoShare.tsx
Close #90 
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/video-share-layout/web/
=> fix: video share layout

web/src/components/SingleRoom.tsx, web/src/hooks/useNicknameMap.ts
Close #91 
useNicknameMap didn't work as expected. Now, it works with a global cache.
The issue was common in video share.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/nickname-map/web/
=> fix: show nickname in screen share

web/src/hooks/useFaceVideos.ts, web/src/network/room.ts
and  improve avoiding negotiation error
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/face-video-stability/web/
=> chore: use mutable stream for faces

web/src/components/MomentaryChat.tsx, web/src/hooks/useMomentaryChat.ts
add emoji picker to chat
Preview URL: https://codesandbox.io/s/github/kobatastu/remote-faces/tree/feat/add-emoji-picker-to-chat/web/
=> add emoji picker to chat

web/src/components/ScreenShare.css, web/src/network/room.ts, web/src/network/trackUtils.ts
- retry negotiation with random timeout
- track ended emulation with transceiver.currentDirection hack
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/network-renegotiation/web/
=> Improve live mode connectivity

web/src/components/App.tsx, web/src/components/GitHubCorner.css, web/src/components/GitHubCorner.tsx
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/github-corner/web/
=> add github corner

web/src/hooks/useFaceVideos.ts
There was an issue in #99. `faceStream` is an mutable object and useEffect doesn't trigger callback with `micOn` changes. This PR fixes with event listeners.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/mic-on-not-working/web/
=> fix: micOn not working

web/src/components/MomentaryChat.tsx, web/src/components/WysiwygEditor.tsx
Close #108 
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/external-link-in-chat/web/
=> fix: external-link-in-chat

web/src/components/MomentaryChat.tsx
I fix the scroll when smoeone add some message
Preview URL: https://codesandbox.io/s/github/kobatastu/remote-faces/tree/feat/add-scroll/web/
=> add scroll

web/src/components/MomentaryChat.tsx, web/src/hooks/useMomentaryChat.ts
Adds randomly unique `messageId` in chat messaage. `createdAt` is also added at the sender.
This fixes a bug in #114 and prepares for #104 .
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/chore/chat-message-id/web/
=> introduce messageId in MomentryChat

web/src/hooks/useFaceImages.ts, web/src/hooks/useMomentaryChat.ts, web/src/hooks/useRoom.ts, web/src/network/room.ts
Close #104 
There's some TODOs in comments.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/notify-new-peer/web/
=> feat: expose notifyNewPeer, and send chat history

web/src/components/FaceImages.css, web/src/components/FaceImages.tsx, web/src/components/MomentaryChat.css, web/src/components/SingleRoom.css
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/setting-hidden/web/
=> fix setting not to be hidden and other style tweaks

web/src/components/FaceImages.css, web/src/components/FaceImages.tsx, web/src/hooks/useFaceImages.ts
It's a small solution to #106 
Added Mic-on and Speaker-on indicators to make it easier to know the status of other users.
Preview URL: https://codesandbox.io/s/github/molmoit/remote-faces/tree/feat/micOn-and-speakerOn-indicator/web/
=> feat: add mic-on and speaker-on indicator on each face

web/src/hooks/useFaceImages.ts
this is to address the issue #128.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/issue-128/web/
=> add didCleanup flag

web/src/components/App.test.tsx, web/src/components/Landing.css, web/src/components/Landing.tsx, web/src/components/SingleRoomEntrance.css, web/src/components/SingleRoomEntrance.tsx, web/src/components/Welcome.css, web/src/components/Welcome.tsx
not fancy just minimum.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/landing-page/web/
=> landing page

web/src/components/ControlPanel.css, web/src/components/MomentaryChat.css, web/src/components/SettingPanel.css, web/src/components/SettingPanel.tsx, web/src/components/SingleRoom.css, web/src/components/UserStatus.css, web/src/components/UserStatus.tsx
close #124 
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/fix/font-size-margin/web/
=> fix: font-size and margin

web/src/components/MomentaryChat.tsx, web/src/components/UserStatus.tsx
The emoji picker didn't fully fit into the MomentryChat column, so I fixed it to fit into the column.
Preview URL: https://codesandbox.io/s/github/molmoit/remote-faces/tree/feat/confine-emoji-picker/web/
=> Confine the emoji picker to the column.

web/package.json, web/src/network/ipfs.d.ts, web/src/network/ipfsRoom.ts, web/src/network/ipfsUtils.ts, web/src/network/peerjsRoom.ts, web/src/network/room.ts, yarn.lock
An opt-in network module with IPFS PubSub.
There's one fundamental issue (topic=userId not working) and the workaround is to use broadcast inefficiently. Should be fixed in the future, by make it work or use lower level API.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/ipfs-pubsub/web/
=> [network] ipfs pubsub

web/src/components/MomentaryChat.tsx, web/src/hooks/useMomentaryChat.ts
Simplifying the code and to make it a small chunk.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/chore/unified-chat-data/web/
=> chore: unified chat data

web/src/network/ipfsRoom.ts, web/src/network/ipfsUtils.ts, web/src/network/peerjsRoom.ts, web/src/network/room.ts, web/src/utils/url.ts
This will make the default network IPFS instead of PeerJS. To use peerjs, it requires `&peerjs=...` option.
It includes some refactoring.
Preview URL: https://codesandbox.io/s/github/dai-shi/remote-faces/tree/feat/make-ipfs-default-network/web/
=> feat: make ipfs default network

.github/pull_request_template.md
=> chore: no pr template

.gitmodules, libopus/Makefile, web/package.json, web/public/audio-decoder.js, web/public/audio-encoder.js, web/public/libopus.js, web/src/hooks/useRoom.ts, web/src/network/common.ts, web/src/network/ipfs.d.ts, web/src/network/ipfsRoom.ts, web/src/network/ipfsUtils.ts, web/src/network/peerjsRoom.ts, web/src/network/pubsubRoom.ts, web/src/network/room.ts, web/src/network/trackUtils.ts, web/src/utils/crypto.ts, web/src/utils/excalidraw.ts, web/src/utils/types.ts, web/src/utils/url.ts, web/yarn.lock
- new room implementation: `pubsubRoom.ts` ("faceAudio" only)
- dynamic imports in room.ts
- cryptoKey instead of string key
- and some others
=> Experimental media in ipfs pubsub with face audio

web/src/hooks/useFaceVideos.ts, web/src/hooks/useRoom.ts, web/src/hooks/useScreenShare.ts, web/src/hooks/useVideoShare.ts
This will now allow `useRoomMedia` from multiple components.
Caution: Only one track can be added. So, there will be primary component that adds local track and secondary component that only listens to remote tracks.
=> chore: refactor useRoomMedia

web/src/components/MomentaryChat.tsx, web/src/hooks/useNotification.ts
close #146 
Desktop notification with chat at mention.
=> feat: chat notification

web/src/components/MomentaryChat.tsx
=> chore: refactor chat text state

web/package.json, web/src/network/ipfsRoom.ts, yarn.lock
This will improve reconnection.
=> fix: update ipfs-pubsub-room for reconnect

web/package.json, web/src/network/ipfsRoom.ts, web/src/network/peerjsRoom.ts, web/src/network/pubsubRoom.ts, web/src/utils/crypto.ts
=> feat: support chunking for ipfsRoom

web/src/components/MomentaryChat.tsx
=> fix: limit chat text size

web/src/network/pubsubRoom.ts, web/src/utils/crypto.ts
Now, 40 audio frames sent at once (60ms x 40 = 2.4sec)
This includes a fix for chunking too.
=> fix: pubsub faceAudio with re-packeting

web/src/network/pubsubRoom.ts, web/src/network/trackUtils.ts
just send jpeg data url every seconds.
=> feat: experimental facevideo in pubsub

web/src/network/peerjsRoom.ts
This fix might be too naive, but it seems to work...
=> fix: peerjs room reconnect

web/src/components/SpatialArea.tsx, web/src/hooks/useSpatialArea.ts
don't send data back and forth 😓
=> feat: improve spatial area drag faces

web/src/hooks/useSpatialArea.ts
don't sync, just send original.
=> feat: simplify avatar sync in spatial area

web/src/components/SpatialArea.tsx
very naive audio control (linear)
=> feat: spatial area audio 1st trial

web/package.json, web/src/components/FaceImages.css, web/src/components/SelectivePane.tsx, web/src/components/SingleRoom.tsx, web/src/components/SpatialArea.tsx, web/src/hooks/useSpatialArea.ts, web/src/media/video.ts, yarn.lock
=> feat: reduce timeout tasks

web/src/components/FaceImages.tsx, web/src/components/Loading.css, web/src/components/Loading.tsx, web/src/components/SuspenseFallback.css, web/src/components/SuspenseFallback.tsx
=> add loading indicator

web/src/network/peerjsRoom.ts, web/src/network/peerjsUtils.ts
=> fix(peerjsRoom): improve reconnect handling

web/src/components/FaceCard.css, web/src/components/FaceCard.tsx, web/src/components/FaceList.tsx, web/src/components/GatherArea.css, web/src/components/GatherArea.tsx, web/src/components/MySetting.tsx, web/src/components/SingleRoomEntrance.tsx, web/src/states/singleRoom.ts
=> add setting menu

web/src/components/GatherArea.tsx, web/src/hooks/useGatherArea.ts, web/src/states/roomPresets.ts
😎 
Currently, all type=background with zIndex=0 is movable. We may introduce a new type=object in the future.
=> feat: movable background

web/src/components/FaceCard.css, web/src/components/FaceCard.tsx, web/src/components/FaceList.tsx, web/src/components/GatherArea.tsx, web/src/media/devices.ts
- show last updated in face card
- but not in gather area
- no status message icon in gather area
- fix video constraint on startup
=> feat: show last updated in face card

web/src/components/MySetting.tsx
If you not set a new avatar image in the setting panel, avatar is not update.
=> fix: avatar update

web/src/network/peerjsRoom.ts
=> fix(peerjsRoom): auto close stale connection

web/src/components/FaceCard.css, web/src/components/FaceCard.tsx, web/src/components/GatherArea.tsx, web/src/components/Landing.tsx
Now, the entire face card on top left is clickable.
=> fix(web): more clickable face card in face list

web/package.json, web/src/components/FaceList.tsx, web/src/components/GatherArea.tsx, web/src/components/GoBoard.css, web/src/components/GoBoard.tsx, web/src/components/RegionEditor.tsx, web/src/hooks/useFaceImages.ts, web/src/hooks/useGatherArea.ts, web/src/hooks/useGoBoard.ts, web/src/hooks/useMomentaryChat.ts, web/src/hooks/useNicknameMap.ts, web/src/states/roomMap.ts, web/src/states/roomPresets.ts, yarn.lock
Very glad to see valtio-yjs really works!
=> feat(web): reafactor with valtio-yjs

web/src/components/GatherArea.tsx, web/src/components/RegionEditor.tsx, web/src/hooks/useGatherArea.ts, web/src/states/roomMap.ts, web/src/states/roomPresets.ts
We didn't need to make it a list, and a map is better to be unique with ids.
=> fix(web): revert to region map

web/src/network/peerjsRoom.ts
No notion of seed peers anymore.
=> feat(web): simplify peerjsRoom logic

web/package.json, web/src/components/FaceCard.tsx, web/src/components/GatherArea.css, web/src/components/GatherArea.tsx, web/src/components/MySetting.tsx, web/src/components/SingleRoomEntrance.tsx, web/src/hooks/useGatherArea.ts
https://user-images.githubusercontent.com/490574/148069960-ecea8bef-4386-4cab-8002-4aa1bd6aedd3.mov
=> feat(web): resize/move/delete region

web/src/components/FaceCard.tsx, web/src/components/GatherArea.tsx
=> feat(web): drop url to create a new region

web/src/components/GatherArea.css, web/src/components/GatherArea.tsx, web/src/hooks/useGatherArea.ts, web/src/states/roomPresets.ts, web/src/utils/base64.ts
=> feat(web): improving drop feature

web/src/components/GatherArea.tsx, web/src/components/RegionEditor.css, web/src/components/RegionEditor.tsx, web/src/hooks/useGatherArea.ts, web/src/states/roomPresets.ts
breaking change: region type `background` 👉 `default`
=> fix(web): improve region editor and so on

web/src/components/GatherArea.tsx, web/src/components/MySetting.css, web/src/components/MySetting.tsx
Sometimes, onPaste is more convenient than onDrop. The code can be mostly in common.
=> feat(web): support pasting texts

web/src/network/peerjsRoom.ts, web/src/network/peerjsUtils.ts
only connect to peers with lower index.
=> fix(web): simplify peerjs room to increase stability

web/src/hooks/useFaceImages.ts
=> fix(web): camera black out

web/src/network/room.ts, web/src/utils/url.ts
=> make peerjs default

web/public/stream_viewer.html, web/src/components/GatherArea.tsx, web/src/components/MeetingScreen.css, web/src/components/MeetingScreen.tsx, web/src/hooks/useGatherArea.ts, web/src/states/roomPresets.ts
It depends on BroadcastChannel. Does it work on Electron?
=> feat: screen share in meeting

web/src/components/MySetting.tsx
There was a regression in #235.
=> fix(web): allow to clear status message

web/src/components/ControlPanel.css, web/src/components/GatherArea.tsx, web/src/components/reusable/MediaShare.tsx, web/src/components/reusable/RegionEditor.tsx, web/src/components/reusable/TalkyStarter.css, web/src/components/reusable/TalkyStarter.tsx, web/src/hooks/useGatherArea.ts
=> feat(web): talky starter and some fixes

web/src/states/roomPresets.ts
=> fix(web): office5 preset

web/src/components/GatherArea.css, web/src/components/MemberList.css, web/src/components/reusable/MeetingScreen.css, web/src/hooks/useGatherArea.ts
=> fix(web): adjust styles
